spring:
  data:
    rest:
      defaultMediaType: application/hal+json
      returnBodyOnCreate: true
      returnBodyOnUpdate: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-dates-with-zone-id: true
    deserialization:
      adjust-dates-to-context-time-zone: false

